### ISSUE TITLE
How to change username?

### ISSUE THREAD

**Issue by WaterSpice** [cosenary/Instagram-PHP-API#110]
Is this possible? I looked over the docs and didn't see this.

I was wondering if this is possible to change your current username to another.

**Comment by vinkla** [comment]
Through the API you mean or Instagram accounts in general?

**Comment by WaterSpice** [comment]
@vinkla I want to be able to change my name via the API.
so like
$instagram->changeUsername('newusername');

something like that... possibly?

**Comment by vinkla** [comment]
No, I don't think so.

**Comment by cosenary** [comment]
Hi, @vinkla is right. This is currently not supported by the Instagram API.
