### ISSUE TITLE
Undefined offset: 1 at vendor/cosenary/instagram/src/Instagram.php on line 494

### ISSUE THREAD

**Issue by bayusuwarninghadi** [cosenary/Instagram-PHP-API#111]
I got Undefined offset: 1
at line
``list($headerContent, $jsonData) = explode("\r\n\r\n", $jsonData, 2);``

**Comment by stefanschindler** [comment]
The same problem exists for me, when calling the `getUserMedia` method

**Comment by bayusuwarninghadi** [comment]
this is because explode("\r\n\r\n", $jsonData, 2), just contain one element of array
for temporary, toggle comment line 494-500
```
    list($headerContent, $jsonData) = explode("\r\n\r\n", $jsonData, 2);
    $headers = $this->processHeaders($headerContent);
    $this->_xRateLimitRemaining = $headers['X-Ratelimit-Remaining'];
```

**Comment by fgt91** [comment]
Sorry to reopen this post...
I got the same problem at the same line as @bayusuwarninghadi resulting in these errors:
`PHP Notice:  Undefined offset: 1 in src/Instagram.php on line 627`
`PHP Fatal error:  Class 'MetzWeb\Instagram\InstagramException' not found in src/Instagram.php on line 637` 
I have this call reiterated over a thousand times for over a thousand of different user ids:
` $instagram->getUser($id); ` 
Errors show up after I call $instagram->getUser($id); over a thousand times... but I don't have even exceeded instagram's api limit...
where might the problem come from?
Hope I explained myself... Thanks! :)
