### ISSUE TITLE
PSR-2 Support

### ISSUE THREAD

**Issue by vinkla** [cosenary/Instagram-PHP-API#114]
What about converting the code to [PSR-2 styled syntax](http://www.php-fig.org/psr/psr-2/)? It can be done fast with [PHP Coding Standards Fixer](http://cs.sensiolabs.org/). I can update the code if you want me to. What do you think?

Later we could perhaps integrate this package with https://styleci.io to check all pull requests automagically before they get merge them in. I use this on [all of my packages](https://github.com/vinkla/instagram/blob/master/.styleci.yml).

**Comment by cosenary** [comment]
Thanks for your vibrant contribution to the project! I think it's a good idea to follow the PHP coding standard, so please feel free to convert the code.

**Comment by vinkla** [comment]
Great! I'm on it. What about integrating https://styleci.io? Maybe you could sign up?

**Comment by vinkla** [comment]
Merged in https://github.com/cosenary/Instagram-PHP-API/commit/0adab45cc27916640b904ff72b773d9ff578255b
