### ISSUE TITLE
getTagMedia, add parameters MIN_TAG_ID and MAX_TAG_ID

### ISSUE THREAD

**Issue by Sudei** [cosenary/Instagram-PHP-API#118]
I notice that your "getTagMedia" is declared  as follow : 
```
public function getTagMedia($name, $limit = 0) { ... }
```
But the Instragram's API Allow 2 more parameters MIN_TAG_ID & MAX_TAG_ID.

Maybe you should change your methode as :
```
  /**
   * Get a recently tagged media.
   *
   * @param string $name                         Valid tag name
   * @param array [optional] $params       Requesting additional parameters
   *
   * @return mixed
   */
  public function getTagMedia($name, $params = array()) {
    return $this->_makeCall('tags/' . $name . '/media/recent', false, $params);
  }
```

**Comment by vinkla** [comment]
Thanks for reaching out. I agree this should be implemented. Maybe you could create a pull request?

**Comment by vinkla** [comment]
@Sudei Just a pointer, if you add something like fixes or closes with the issue number after this will be closed automatically when your pull request gets merged.
