### ISSUE TITLE
Count parameter in multiple methods aren't working

### ISSUE THREAD

**Issue by BeachPeach** [cosenary/Instagram-PHP-API#122]
I have successfully installed the example but when I am trying to use methods such as 
* getUserLikes()
* getUserFeed()
* getTagMedia($searchTerm)

If I am not specifying a number as a limit I receive to following as a result : 
`object(stdClass)#4 (1) { ["meta"]=> object(stdClass)#5 (3) { ["error_type"]=> string(25) "APIInvalidParametersError" ["code"]=> int(400) ["error_message"]=> string(31) "Count must be larger than zero." } }`

I have no problem specifying the number of item I need but I thought I might be missing something and if not, that we should correct the documentation.

**Comment by vinkla** [comment]
Thanks for reaching out. Seems Instagram recently has done something with their API. Until we address and fix this bug, you could try to specify the `$limit` parameter in the method calls.

This issue is also discussed in #120 and #121.

**Comment by BeachPeach** [comment]
My bad.
As this issue is addressed in other threads I'll close this one.
Thanks for your help!

**Comment by vinkla** [comment]
No problem. I think it is good developers are reaching out. The more the better.
