### ISSUE TITLE
Pagination doesn't seem to be working

### ISSUE THREAD

**Issue by StephaneTurquay** [cosenary/Instagram-PHP-API#145]
HI,

I'm trying to get more than 20 items while using searchMedia() so the function pagination() was supposed to answer to my needs. However, it doesn't seem to be working even when using the snippet provided in the readme.

ErrorException in Instagram.php line 383: Undefined property: stdClass::$pagination

Did I miss something?

Thanks in advance.

**Comment by coreequip** [comment]
searchMedia() doesn't support pagination. Please see [the returned JSON](https://github.com/cosenary/Instagram-PHP-API/wiki/Media-resources#search-media). There is no "pagination"-property.

See also [stackoverflow](http://stackoverflow.com/a/21593420). Sorry,

**Comment by StephaneTurquay** [comment]
Thank you for the answer.
