### ISSUE TITLE
Does not work with composer

### ISSUE THREAD

**Issue by pronebird** [cosenary/Instagram-PHP-API#146]
Hi,

Suddenly the same installation that works on my Mac does not work on Ubuntu server.

Getting this:

```
PHP Fatal error:  Class 'MetzWeb\\Instagram\\Instagram' not found
```

**Comment by vinkla** [comment]
Please provide a more information. Just saying that it doesn't work makes it hard for us to help you.

**Comment by pronebird** [comment]
I am currently trying to wipe vendor/ folder and regenerate autoloader with new composer. It could not find a class apparently.

**Comment by pronebird** [comment]
Hey sorry for false alarm. Apparently that was an issue between diff versions of composer and new composer did not bother to regenerate the boilerplate for autoloader.
