### ISSUE TITLE
request

### ISSUE THREAD

**Issue by 91521068** [cosenary/Instagram-PHP-API#164]
Hello
excuse me. my English writing is bad.
i need a forced SIGNED key that have permission of like.
instagram policy have been changed. and new public app can not access to like endpoint.
Link(http://developers.instagram.com/post/116410697261/publishing-guidelines-and-signed-requests)
do you have any key with permission of like?
i can buy it from you .( or i can give 15% of my sell to you .) if you give me a key with like permission

i promise you that i use it only in my application.
and my application is valid in (TERMS OF USE) of instagram.

please reply to my message for more speeking about it.
mehdi.bagvand@gmail.com

thanks.

**Comment by johannesnagl** [comment]
spam!

**Comment by 91521068** [comment]
No.
I can show my app to you.

And you can disable it every time that is spam.

This isnt spam. Please read it carefully.
Thanks.

**Comment by johannesnagl** [comment]
no one will ever give you his/her app id/app secret. as described here (https://github.com/cosenary/Instagram-PHP-API/issues/152), only instagram is able to grant you the mentioned permission.

**Comment by johannesnagl** [comment]
btw: it's definitely spam, if you ask the same question over and over again: (https://github.com/Instagram/python-instagram/issues/170)

**Comment by 91521068** [comment]
But instagram policy changed.
And i can not have application that made for public people.
So only way is (some one give me a key)

**Comment by 91521068** [comment]
You can read link that i posted and you will realize it.
Do you have any key to help me?

**Comment by 91521068** [comment]
I can give you feather of my sell.

**Comment by johannesnagl** [comment]
i know of the api change. but as said before: no one will ever give you his/her key.

**Comment by 91521068** [comment]
i think key is not very secret because below library share it.

https://github.com/thiagolocatelli/android-instagram-oauth/blob/master/android-instagram-oauth-example/src/br/com/dina/oauth/instagram/example/ApplicationData.java

Thanks forever.

**Comment by johannesnagl** [comment]
you never should share your SECRET with anyone else (else it's no secret anymore, isn't it?)

[i love you.](http://www.hexjam.com/uk/sex-relationships/i-spent-a-month-replying-to-all-of-my-pr-emails-with-i-love-you)

**Comment by 91521068** [comment]
yes
it is secret because if any more people that know your secret key then they can use it and its limit reach.

and you application that use this key will not work (because of limit)
but now.
i want a key from you that you dont need it (means: you dont have any app that use it).

**Comment by 91521068** [comment]
this task is risk for me.
because you can every time reset secret key and my application will not work.

**Comment by vinkla** [comment]
Closing this due to stranger danger. Never share your credentials!
