### ISSUE TITLE
Undefined property: stdClass::$pagination

### ISSUE THREAD

**Issue by DeeJaVu** [cosenary/Instagram-PHP-API#173]
i dont understand how i can do the pagination for getPopularMedia()

code of my controller is

    $popular = $this->instagram->getPopularMedia();
    $testp = $this->instagram->pagination($popular);
when i return $testp i get a Undefined property: stdClass::$pagination error

what am i doing wrong ?

**Comment by bodva** [comment]
popular media does not have pages, see in instagram api documentation.

**Comment by DeeJaVu** [comment]
aahhhahah ok :D
