### ISSUE TITLE
Receiving: Notice: Undefined property: stdClass

### ISSUE THREAD

**Issue by esteban1972** [cosenary/Instagram-PHP-API#21]
This is my first time working with cosenary. So far, good. But when I try to autenticate access some private methods I receive "Notice: Undefined property: stdClass" when I call "setAccessToken". Here is some sample code:

<?php
require_once("conf.php");
require_once("instagram.class.php");

session_start();

$instagram = new Instagram(INSTAGRAM_CLIENT_ID, INSTAGRAM_CLIENT_SECRET);

$code = "111111122222233333344444";
$token = $instagram->getOAuthToken($code, true);
$_SESSION['access_token'] = $token;

$instagram->setAccessToken($token);

?>

Any help?

Thanks

**Comment by lodotek** [comment]
I too am getting the same error:   Undefined property: stdClass::$access_token in /var/www/html/includes/instagram.php on line 523

What specifically do I need to do to fix this?
