### ISSUE TITLE
Errror when developing  locally

### ISSUE THREAD

**Issue by jamoir** [cosenary/Instagram-PHP-API#61]
Hi,

I've got the following error when testing a local script:

Error: _makeCall() - cURL error: Failed to connect to 173.252.114.3: Host is down

I've made sure the cURL options are set:

curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);  

But it makes no difference.

I'm using the open access option to get media.

$search_data = $instagram->getMedia('769610294212249053_13460080');

Copied to a live server this works fine.

Thanks for your help.

Jamie

**Comment by robertark** [comment]
This sounds like you might be behind a proxy.
