### ISSUE TITLE
Add X-RateLimit-Remaining API

### ISSUE THREAD

**Issue by gmisura** [cosenary/Instagram-PHP-API#80]
When calling the instagram API, you're limited to 5000 calls per hour per token.
It would be very useful if your class/code had an attribute that stored that info so I could keep track of where my users are in their current hour's limit.

Is there a call to be made that will give the current limit without expending 1 call? Doesn't seem like it.

**Comment by GMusliaj** [comment]
Or maybe you could just add a counter separately inside the code which logs every api call.

**Comment by gmisura** [comment]
A counter inside the code doesn't make sense. How does the code know if you've made other calls using a given token and thus used more of your 5000 hourly limit. Really, the only option is to return the authoritative results: Instagram's header.

**Comment by GMusliaj** [comment]
Well, it does make sense if you are not given any other option. You could challenge yourself and implement a server side db solution which counts every api call made by all your clients etc etc (meaning you will 'reinvent the wheel'). Anyway if Instagram would provide this via its headers would be much more appreciated.

**Comment by gmisura** [comment]
Instagram _DOES_ provide it via the headers...

**Comment by GMusliaj** [comment]
Hey, 
check out my response here http://stackoverflow.com/questions/27586025/instagram-api-access-rate-limit-information-with-specific-php-class/27761804#27761804 because I resolved the problem with X-Ratelimit-Remaining. No expending calls, it simply works perfectly :) Let me know if you have any issue

**Comment by robertark** [comment]
@GMusliaj you should submit a pull request ;) I would be interested in this as well.

**Comment by GMusliaj** [comment]
@robertark done! :)

**Comment by cosenary** [comment]
Thanks :)
