### ISSUE TITLE
How to logout automatically when add another instagram account?

### ISSUE THREAD

**Issue by hoa2ng** [cosenary/Instagram-PHP-API#82]
Hi guys,
I am following the answer below (append a iframe tag after body tag) to logout current instagram account when add a new other account ( my application allows to add many instagram account )

http://stackoverflow.com/questions/23279689/php-instagram-api-user-logout

it's working on chrome but not working on safari.. I really know why??

please help me

Thanks in advance

**Comment by cosenary** [comment]
Hi!
The issue with Safari seems to be, that it blocks any session interaction through iframes. Thus, the active Instagram session won't be deleted. An alternative I can think of, is to trigger an AJAX call like this:

```js
$.ajax({
  method: 'GET',
  url: 'https://instagram.com/accounts/logout/',
  success: function(result) {
      console.log('you have been successfully logged out');
  },
  error: function(error) {
      console.error('an error occured: ' + error.responseText);
  }
});
```

I haven't tested this, but this could be a cross-browser solution. Let me know if this works for you.
Christian

**Comment by bunleo** [comment]
Hi @cosenary 
Thanks for your answer. it's working now :). 
In additional, I can use piece of the following codes :

```javascript
var iframe = document.getElementById('logoutIframe');
iframe.src = "https://instagram.com/accounts/logout";
document.getElementById('logoutIframe').reload(true);
document.body.appendChild(iframe);
```
I think the difference between my way and the way on stackoverflow is :
```javascript
document.getElementById('logoutIframe').reload(true);
```
Do you think so?

**Comment by cosenary** [comment]
Great to hear that it's working now!
According to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/HTMLIFrameElement.reload), `reload(true)` forces all loaded resources to be re-checked for expiry at the server.
Thanks for sharing your way. It's a good reference for everyone who faces a similar issue.

Cheers,
Christian
